### PR TITLE
Updated send email to handle html body

### PR DESCRIPTION
**Pull request by sinarest1608**
**What does this change do?** _Please be clear and concise._

Changes `send_email()` function to handle `html` content in the body. Strings in body have no impact and render as usual.

**Why was this change made?** _Including an issue number is sufficient. Otherwise, briefly explain the benefit of the change._

`send_email()` parsed the html code in the body as string and sent the complete code instead of rendering the html. 

## Verification

NA

## Affirmations

All of these should have a check by them. Any exception requires an explanation.

* [x] I have added docstrings with details on keyword arguments to new functions following the convention detailed in this [gist](https://gist.github.com/mbentz-uf/0433c32f260a0a06f57a9ff32fcef252)
* [x] I have added type hinting to new function parameters.
* [x] I have added tests to new functions, following the rules of [F.I.R.S.T.](https://wiki.ctsi.ufl.edu/books/testing/page/how-to-write-python-unit-tests).
* [x] I matched the style of the existing code.
* [x] I added and updated any relevant documentation (inline, `README`, `CHANGELOG`, and such).
* [x] I used Python's type hinting.
* [x] I ran the automated tests and ensured they **ALL** passed.
* [x] I ran the linter and ensured my changes have not introduced **ANY** warnings or errors.
* [x] I have made an effort to minimize code changes and have not included any cruft (preference files, *.pyc files, old comments, print-debugging, unused variables).
* [x] I have made an effort maintain a clear commit history (haven't merged other branches or rebased improperly).
* [x] I have written the code myself or have given credit where credit is due.

### CODE REVIEW

**Comment by mehuljhaver4** [comment]
- You can remove the print statements on line 98 and 101
- The code in general works as expected. 
- Not sure if we will have this edge case but it fails when there's "\n" and "<html tag>" in the body of the message.
- Example: "This is \n a Python Script. <p> Testing the script"

**Review by mehuljhaver4 — COMMENTED** [review]
- You can remove the print statements on `line 98 and 101`
- The code in general works as expected. 
- Not sure if we will have this edge case but it fails when there's `"\n"` and `"<some html tag>"` in the body of the message.
- Example: `"This is \n a Python Script. <p> Testing the script"`

**Comment by sinarest1608** [comment]
@mehuljhaver4 
I have removed the print statements. 
Yes the edge case is a valid one but i'm also not sure if we would ever face this case. 
@mbentz-uf what do you think?

**Comment by sinarest1608** [comment]
@mbentz-uf 
Mehul reviewed the code but is not able to merge it. Can you help with the merge?

**Review by michael-bentz — APPROVED** [review]

**Comment by michael-bentz** [comment]
@mehuljhaver4 Can you try now?

**Comment by michael-bentz** [comment]
#3 would be a nice-to-have in the future.

**Comment by mehuljhaver4** [comment]
> @mehuljhaver4 Can you try now?

Merging is still blocked @mbentz-uf

**Pull request merged**
